config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :cart_products
  resources :product_images
  resources :product_reviews
  resources :product_categories
  resources :payments
  resources :order_items
  resources :order_states
  resources :user_addresses
  resources :user_roles
  resources :reports
  resource :cart, only: [:show, :destroy] do
    post 'add_product/:product_id', to: 'carts#add_product', as: 'add_product'
    post 'update_quantity/:product_id', to: 'carts#update_quantity', as: 'update_quantity'
    post 'remove_product/:product_id', to: 'carts#remove_product', as: 'remove_product'
    # Nuevas rutas para los usuarios registrados
    delete 'remove2/:product_id', to: 'carts#remove_product2', as: 'remove_product2'
    patch 'update_quantity2/:product_id', to: 'carts#update_quantity2', as: 'update_quantity2'
    # Rutas para el pago
    get 'checkout', to: 'carts#checkout', as: 'checkout'
    get 'payment_confirmation', to: 'carts#payment_confirmation', as: 'payment_confirmation'
  end
  resources :products
  resources :orders
  resources :users
  resources :categories
  resources :payment_methods
  resources :payment_states
  resources :roles
  resources :states
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
  has_one :order

  def total_price
    cart_products.sum { |cart_product| cart_product.product.price * cart_product.quantity }
  end
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  validates :quantity, numericality: { greater_than: 0 }
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_one :payment
  has_one :order_state
  belongs_to :cart, optional: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order_state.rb
class OrderState < ApplicationRecord
  belongs_to :order
  belongs_to :state
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
  belongs_to :payment_state
  belongs_to :payment_method
end

app/models/payment_state.rb
class PaymentState < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products
  has_many :carts, through: :cart_products
  has_many :order_items

  has_many :product_categories
  has_many :categories, through: :product_categories
  
  has_many :product_reviews
  has_many :product_images

  has_many_attached :images
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["name", "description", "price"] # Agrega los atributos que deseas permitir que Ransack busque
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :orders, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :user_role
  has_many :roles, through: :user_role
  has_many :user_addresses

  after_create :create_cart

  def administrador?
    roles.exists?(name: 'Administrador') # Asegúrate de que 'Administrador' sea el nombre correcto del rol
  end

  def create_cart
    Cart.create(user: self)
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/order_states_controller.rb
class OrderStatesController < ApplicationController
  before_action :set_order_state, only: %i[ show edit update destroy ]

  # GET /order_states or /order_states.json
  def index
    @order_states = OrderState.all
  end

  # GET /order_states/1 or /order_states/1.json
  def show
  end

  # GET /order_states/new
  def new
    @order_state = OrderState.new
  end

  # GET /order_states/1/edit
  def edit
  end

  # POST /order_states or /order_states.json
  def create
    @order_state = OrderState.new(order_state_params)

    respond_to do |format|
      if @order_state.save
        format.html { redirect_to @order_state, notice: "Order state was successfully created." }
        format.json { render :show, status: :created, location: @order_state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_states/1 or /order_states/1.json
  def update
    respond_to do |format|
      if @order_state.update(order_state_params)
        format.html { redirect_to @order_state, notice: "Order state was successfully updated." }
        format.json { render :show, status: :ok, location: @order_state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_states/1 or /order_states/1.json
  def destroy
    @order_state.destroy

    respond_to do |format|
      format.html { redirect_to order_states_path, status: :see_other, notice: "Order state was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_state
      @order_state = OrderState.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_state_params
      params.require(:order_state).permit(:order_id, :state_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_states_helper.rb
module OrderStatesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/order_states/_form.html.erb
<%= form_with(model: order_state) do |form| %>
  <% if order_state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order_state.errors.count, "error") %> prohibited this order_state from being saved:</h2>

      <ul>
        <% order_state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id %>
  </div>

  <div>
    <%= form.label :state_id, style: "display: block" %>
    <%= form.text_field :state_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/order_states/_order_state.html.erb
<div id="<%= dom_id order_state %>">
  <p>
    <strong>Order:</strong>
    <%= order_state.order_id %>
  </p>

  <p>
    <strong>State:</strong>
    <%= order_state.state_id %>
  </p>

</div>

app/views/order_states/edit.html.erb
<h1>Editing order state</h1>

<%= render "form", order_state: @order_state %>

<br>

<div>
  <%= link_to "Show this order state", @order_state %> |
  <%= link_to "Back to order states", order_states_path %>
</div>

app/views/order_states/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Order states</h1>

<div id="order_states">
  <% @order_states.each do |order_state| %>
    <%= render order_state %>
    <p>
      <%= link_to "Show this order state", order_state %>
    </p>
  <% end %>
</div>

<%= link_to "New order state", new_order_state_path %>

app/views/order_states/new.html.erb
<h1>New order state</h1>

<%= render "form", order_state: @order_state %>

<br>

<div>
  <%= link_to "Back to order states", order_states_path %>
</div>

app/views/order_states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order_state %>

<div>
  <%= link_to "Edit this order state", edit_order_state_path(@order_state) %> |
  <%= link_to "Back to order states", order_states_path %>

  <%= button_to "Destroy this order state", @order_state, method: :delete %>
</div>